name: reference

on:
  pull_request:
    branches-ignore:
      - 'gh-pages'

env:
  GH_TOKEN_DISPATCH: ${{ secrets.GH_TOKEN_DISPATCH }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Build
        run: ${GITHUB_WORKSPACE}/.github/actions/build.sh
