on:
  push:
    branches-ignore:
      - 'gh-pages'
    tags-ignore:
      - '*'
  workflow_dispatch:
env:
  GH_TOKEN_DISPATCH: ${{ secrets.GH_TOKEN_DISPATCH }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17.0
        uses: actions/setup-node@v1
      - name: Build
        run: ${GITHUB_WORKSPACE}/.github/actions/build.sh
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            build/*.zip
      - name: Dispatch Build Request
        run: ${GITHUB_WORKSPACE}/.github/actions/dispatch.sh 'rwinch/spring-reference' "$GH_TOKEN_DISPATCH"
